### ISSUE TITLE
「絵文字をつくりたい」の回答が不適切

### ISSUE THREAD

**Issue by mikecat** [IchigoJam/ichigojam-qa#1]
> 絵文字パターンが書き込まれたメモリのアドレス#700から#FFFを変更するとオリジナル絵文字がつくれる。

とあり、間違っていると断言はできませんが、キャラクターパターンが格納されているのは #7FF までであり、#800 以降を変更すると絵文字への影響は少なく、プログラムが壊れるなどの害が出る可能性があるため、不適切であると考えられます。

**Comment by taisukef** [comment]
ありがとうございます！
修正しました
