### ISSUE TITLE
「なぜIchigoJamはインタプリタなのか」の回答が途中で切れている

### ISSUE THREAD

**Issue by mikecat** [IchigoJam/ichigojam-qa#2]
> 理由は3つ。インタプリタの方がどこで間違ったかがわかりやすい。コンパイルしたバイナリを置くメモリを

「理由は3つ」と書かれているのに、2つしか書かれていないように見え、しかも2つ目は途中で切れているようです。

**Comment by taisukef** [comment]
ありがとうございます！
修正しました
